StudyCatalog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include , url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('profiles.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url('', include('django.contrib.auth.urls')) ,
    url(r'^auth/', include('social_django.urls', namespace='social')),  
    url(r'^$', views.home, name='home'),
    url(r'^post/', views.post_new, name='post_new'),
    url(r'^post-delete/', views.post_delete, name='post_delete'),
    url(r'^comment/', views.comment_new, name='comment_new'),
    url(r'^comment-delete/', views.comment_delete, name='comment_delete'),
    url(r'^votes/', views.post_votes, name='post_votes'),
    url(r'^posts/(?P<pk>\d+)$', views.user_posts, name='user_posts'),
    url(r'^edit-post/', views.edit_posts, name='edit_post'),
    url(r'^edit-profile', views.edit_profile, name='edit-profile'),
    url(r'^profile/(?P<pk>\d+)$', views.profile_detail, name='profile-detail'),
    url(r'^p(?P<pk>\d+)$', views.post_detail, name='post-detail'),
    url(r'^upload-resource/', views.upload_resource, name='upload-resource'),
    url(r'^create-course/', views.create_course, name='create-course'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^catalog/course/(?P<pk>\d+)$', views.course_detail, name='course-detail'),
    url(r'^catalog/department/(?P<pk>\d+)$', views.department_courses, name='department-courses'),
    url(r'^catalog/course/(?P<pk>\d+)/folder/(?P<pk1>\d+)/$', views.folder_detail, name='folder-detail'),
    url(r'^approve-course/', views.approve_course, name='approve-course'),
    url(r'^reject-course/', views.reject_course, name='reject-course'),
    url(r'^approve-resource/', views.approve_resource, name='approve-resource'),
    url(r'^reject-resource/', views.reject_resource, name='reject-resource'),
    url(r'^approve-admin/', views.approve_admin, name='approve-admin'),
    url(r'^reject-admin/', views.reject_admin, name='reject-admin'),
    url(r'^admin-request/', views.admin_request, name='admin-request'),
    url(r'^create-folder/', views.create_folder, name='create-folder'),
    url(r'^folders/$', views.folders, name='folders'),
    url(r'^search/$', views.SearchListView, name='search_list_view'),
    url(r'^delete-resource/(?P<pk>\d+)$', views.delete_resource, name='delete-resource'),
    url(r'^delete-folder/(?P<pk>\d+)$', views.delete_folder, name='delete-folder'),
    url(r'^rename-resource/', views.rename_resource, name='rename-resource'),
    url(r'^rename-folder/', views.rename_folder, name='rename-folder'),
]

profiles/models.py
from django.db import models
import uuid
from django.urls import reverse
from django.contrib.auth.models import User

DEPARTMENTS = (
        ('CSE', 'Computer Science and Engineering'),
        ('CE', 'Chemical Engineering'),
        ('BT', 'Bio-Technology'),
        ('CST', 'Chemical Science & Technology'),
        ('CE', 'Civil Engineering'),
        ('ECE', 'Electronics & Communication Engineering'),
        ('EEE', 'Electronics & Electrical Engineering'),
        ('EP', 'Engineering Physics'),
        ('ME', 'Mechanical Engineering'),
        ('MNC', 'Mathematics & Computing'),
        ('OT', 'Other')
    )

DEGREES = (
        ('PhD', 'Doctorate of Philosophy'), 
        ('B.Tech', 'Bachelor of Technology'), 
        ('M.Tech', 'Master of Technology'), 
        ('B.Des', 'Bachelor of Design'),
        ('M.Des', 'Master of Design')
    )

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, related_name='author',on_delete=models.CASCADE)
    upvote = models.ManyToManyField(User, related_name='upvotes')
    downvote = models.ManyToManyField(User, related_name='downvotes')
    vote_count = models.IntegerField(default = 0)
    
    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])

    def __str__(self):
        return "%s (%s)" % (self.title, self.author.username)

class Comment(models.Model):
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)

class Course(models.Model):
    department = models.CharField(max_length=3, choices=DEPARTMENTS, blank=True, help_text='Department')
    degree = models.CharField(max_length=6, choices=DEGREES, blank=True, help_text='Degree')
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20, blank=True)
    approved = models.BooleanField(default=False)
    admin = models.ForeignKey(User, related_name='admin', on_delete=models.CASCADE, null=True)
    def __str__(self):
        return "%s" % self.name

class Profile(models.Model):
    department = models.CharField(max_length=3, choices=DEPARTMENTS, blank=True, help_text='Department')
    age = models.IntegerField()
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    degree = models.CharField(max_length=6, choices=DEGREES, blank=True, help_text='Degree')
    description = models.CharField(max_length=255, blank=True)
    profile_picture = models.ImageField(upload_to='images/profile_pictures',
                                        default="images/profile_pictures/default.png")
    city = models.CharField(max_length=255)
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    admin = models.BooleanField(default=False)
    admin_dept = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('profile-detail', args=[str(self.id)])

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

class Folder(models.Model):
    title = models.CharField(max_length=200, default='New Folder')
    # folders = models.ManyToManyField("self", symmetrical=False)
    parent_folder = models.ForeignKey("self", related_name="subfolders", on_delete=models.CASCADE, null=True, blank=True)
    course = models.ForeignKey(Course, related_name="folders", on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    root = models.BooleanField(default=False)

    def __str__(self):
        return "%s" % self.title

class Resource(models.Model):
    title = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    course = models.ForeignKey(Course, related_name='resources', on_delete=models.CASCADE)
    file = models.FileField(upload_to='resources/')
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    uploaded_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    folder = models.ForeignKey(Folder, related_name="resource", on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % self.title

profiles/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.utils import timezone
from profiles.models import Post, Comment, Profile, Resource, Course, Folder
from profiles.forms import ProfileForm, ResourceForm, CourseForm
from django.views import generic
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.db import connection
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

DEPARTMENTS = (
        (0, 'CSE', 'Computer Science and Engineering'),
        (1, 'CE', 'Chemical Engineering'),
        (2, 'BT', 'Bio-Technology'),
        (3, 'CST', 'Chemical Science & Technology'),
        (4, 'CE', 'Civil Engineering'),
        (5, 'ECE', 'Electronics & Communication Engineering'),
        (6, 'EEE', 'Electronics & Electrical Engineering'),
        (7, 'EP', 'Engineering Physics'),
        (8, 'ME', 'Mechanical Engineering'),
        (9, 'MNC', 'Mathematics & Computing'),
        (10, 'OT', 'Other')
    )

def home(request):

	user = request.user
	if not request.user.is_authenticated:
		all_posts = Post.objects.all()
		courses = Course.objects.all()
		course_form = CourseForm()
		template_data = {'posts' : all_posts, 'courses': courses, 'course_form': course_form}
		return render(request, 'home.html', template_data)
	
	try:
		profile = Profile.objects.get(user=request.user)
	except Profile.DoesNotExist:
		return HttpResponseRedirect(reverse("edit-profile"))
	
	all_posts = Post.objects.all()
	courses = Course.objects.all()
	course_form = CourseForm()
	template_data = {'posts' : all_posts, 'courses': courses, 'course_form': course_form}
	return render(request, 'home.html', template_data)
	

def post_new(request):
	if request.method == "POST":
		post = Post()
		post.title = request.POST['title']
		post.author = request.user
		post.created_on = timezone.now()
		post.content = request.POST['data']
		post.upvote_count = 0
		post.save()
	all_posts = Post.objects.all()
	template_data = {'posts' : all_posts}
	return render(request, 'post.html', template_data)

def post_delete(request):
	if request.method == "POST":
		post_id = request.POST['post_id']
		post = Post.objects.get(id=post_id)
		comments = Comment.objects.filter(post=post)
		for comment in comments.all():
			comment.delete()
		post.delete()
	all_posts = Post.objects.all()
	template_data = {'posts' : all_posts}
	return render(request, 'home.html', template_data)

def edit_posts(request):
	if request.method == "POST":
		post_id = request.POST['post_id']
		post = Post.objects.get(id=post_id)
		post.title = request.POST['title']
		post.created_on = timezone.now()
		post.content = request.POST['data']
		post.save()
	return HttpResponseRedirect(reverse('post-detail', args=(post.id,)))

def comment_new(request):
	if request.method == "POST":
		comment = Comment()
		post_id = request.POST['post-id']
		comment.post = Post.objects.get(id=post_id)
		comment.author = request.user
		comment.created_on = timezone.now()
		comment.content = request.POST['data']
		comment.save()
	all_posts = Post.objects.all()
	template_data = {'posts' : all_posts}
	return render(request, 'home.html', template_data)


def comment_delete(request):
	if request.method == "POST":
		comment_id = request.POST['comment_id']
		comment = Comment.objects.get(id=comment_id)
		comment.delete()
		
	all_posts = Post.objects.all()
	template_data = {'posts' : all_posts}
	return render(request, 'home.html', template_data)


def user_posts(request, pk):
	user = User()
	user = User.objects.get(id=pk)
	posts = Post.objects.filter(author=user)
	template_data = {'posts' : posts, 'profile': True}
	return render(request, 'home.html', template_data)

def post_votes(request):
	if request.method == "POST":
		post_id = request.POST['post_id']
		upvote = request.POST['upvote']
		downvote = request.POST['downvote']
		down_remove = request.POST['down_remove']
		up_remove = request.POST['up_remove'] 
		post = Post.objects.get(id=post_id)
		if(upvote == "1"):
			post.upvote.add(request.user)
			post.vote_count = post.vote_count + 1
		if(up_remove == "1"):
			post.upvote.remove(request.user)
			post.vote_count = post.vote_count - 1
		if(down_remove == "1"):
			post.downvote.remove(request.user)
			post.vote_count = post.vote_count + 1			
		if(downvote == "1"):
			post.downvote.add(request.user)
			post.vote_count = post.vote_count - 1
		post.save()
	all_posts = Post.objects.all()
	template_data = {'posts' : all_posts}
	return render(request, 'home.html', template_data)

def profile_detail(request, pk):
	profile = Profile.objects.filter(user_id=pk)
	if profile.count() == 0:
		return HttpResponseRedirect(reverse("edit-profile"))
	user = User()
	user = User.objects.get(id=pk)
	posts = Post.objects.filter(author=user)
	template_data = {'posts' : posts, 'profile': profile[0]}
	return render(request, 'profiles/profile_detail.html', template_data)  

def edit_profile(request):
	user = request.user
	if not request.user.is_authenticated:
		return render(request, 'profile_form.html')
	profile = Profile(user=user)
	if request.method == "POST":
		form = ProfileForm(request.POST, request.FILES, instance=profile)
		if form.is_valid():
			form.save()
			profile.save()
			return HttpResponseRedirect(reverse("profile-detail", args=(user.id,)))
	else:
		form = ProfileForm()
	return render(request, 'profile_form.html', context={'form': form})

def post_detail(request, pk):
	post = Post.objects.filter(pk=pk)
	if post.count() == 0:
		return HttpResponseRedirect(reverse("post_new"))
	return render(request, 'post/post_detail.html', context={'post': post[0]}) 

def upload_resource(request):
	form = ResourceForm(request.POST, request.FILES)
	if form.is_valid():
		for file1 in request.FILES.getlist('files'):
			resource = Resource(file=file1, approved=False, user=request.user)
			resource.title = file1.name
			resource.course = Course.objects.get(id=request.POST['course'])
			resource.folder = Folder.objects.get(id=request.POST['folder'])
			resource.save()
	return HttpResponseRedirect(reverse("folder-detail", args=(request.POST['course'], request.POST['folder'],)))

def create_course(request):
	course = Course(approved=False, admin=request.user)
	if request.method == "POST":
		form = CourseForm(request.POST, instance=course)
		if form.is_valid():
			new_course = form.save()
			profile = Profile.objects.filter(user=request.user).first()	
			# profile.admin_of_courses.add(new_course)
			profile.save()
	return HttpResponseRedirect(reverse("home"))

def catalog(request):

	if not request.user.is_authenticated:
		all_posts = Post.objects.all()
		courses = Course.objects.all()
		course_form = CourseForm()
		template_data = {'posts' : all_posts, 'courses': courses, 'course_form': course_form}
		return render(request, 'home.html', template_data)
	
	try:
		profile = Profile.objects.get(user=request.user)
	except Profile.DoesNotExist:
		return HttpResponseRedirect(reverse("edit-profile"))
	


	profile = Profile.objects.filter(user=request.user).first()
	template_data = dict()
	template_data['departments'] = DEPARTMENTS
	all_course_requests = Course.objects.filter(approved=False)
	all_resource_requests = Resource.objects.filter(approved=False)
	template_data['course_requests'] = all_course_requests
	template_data['resource_requests'] = all_resource_requests
	
	if profile.admin:
		template_data['all_admin'] = True
	else:
		template_data['all_admin'] = False

	if profile.admin_dept:
		template_data['dept_admin'] = True
	else:
		template_data['dept_admin'] = False

	return render(request, 'catalog.html', template_data)

def approve_course(request):
	template_data = dict()
	if request.method == "POST":
		course_id = request.POST['course_id']
		course = Course.objects.get(id=course_id)
		course.approved = True
		course.name = request.POST['course_name']
		course.save()
	return HttpResponseRedirect(reverse("catalog"))

def reject_course(request):
	template_data = dict()
	if request.method == "POST":
		course_id = request.POST['course_id']
		course = Course.objects.get(id=course_id)
		profiles = Profile.objects.all()
		for profile in profiles:
			if course in profile.admin_of_courses.all():
				profile.admin_of_courses.remove(course)
		course.delete()
	return HttpResponseRedirect(reverse("catalog"))

def approve_resource(request):
	template_data = dict()
	if request.method == "POST":
		resource_id = request.POST['resource_id']
		resource = Resource.objects.get(id=resource_id)
		resource.title = request.POST['resource_name']
		resource.tag = request.POST['tag']
		resource.approved = True
		resource.save()
	return HttpResponseRedirect(reverse("catalog"))

def reject_resource(request):
	template_data = dict()
	if request.method == "POST":
		resource_id = request.POST['resource_id']
		resource = Resource.objects.get(id=resource_id)
		resource.delete()
	return HttpResponseRedirect(reverse("catalog"))

def admin_request(request):
	template_data = dict()
	if request.method == "POST":
		user_id = request.POST['user_id']
		user = Profile.objects.get(user=user_id)
		user.admin_request = True
		user.save()
	return HttpResponseRedirect(reverse("home"))

def approve_admin(request):
	template_data = dict()
	if request.method == "POST":
		user_id = request.POST['user_id']
		user = Profile.objects.get(user=user_id)
		user.admin_request = False
		user.admin = True
		user.save()
	return HttpResponseRedirect(reverse("catalog"))

def reject_admin(request):
	template_data = dict()
	if request.method == "POST":
		user_id = request.POST['user_id']
		user = Profile.objects.get(user=user_id)
		user.admin_request = False
		user.save()
	return HttpResponseRedirect(reverse("catalog"))

def create_folder(request):
	folder = Folder()
	folder.title = request.POST['title']
	if folder.title == '':
		folder.title = "New Folder"
	folder.course = Course.objects.get(id=request.POST['course_id'])

profiles/templates/profiles/profile_detail.html
{% extends "base.html" %}

{% block profile %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">

    <div class="main-container">
        <div class="container">
            <div class="row">
                <div class="well profile">
                    <div class="col-sm-12">
                        <div class="col-xs-12 col-sm-8">
                            <h2>{{ profile.first_name}} {{ profile.last_name }}</h2><br>
                            <p><strong>About: </strong> {{ profile.description }} </p>
                            <p><strong>Department: </strong> {{ profile.department }} ({{profile.degree}}) </p>
                            <p><strong>City: </strong> {{ profile.city }} </p>
                            <p><strong>Age: </strong> {{ profile.age }} </p><br>
                        </div>             
                        <div class="col-xs-12 col-sm-4 text-center">
                            <figure>
                                <figcaption class="ratings">
                                    <img src="{{profile.profile_picture.url}}" class="avatar img-circle img-thumbnail" alt="avatar">
                                </figcaption>
                            </figure>
                        </div>
                    </div>      
                    <br>      
                    <div class="col-xs-12 divider text-center">
                        <br>
                        <div class="col-xs-12 col-sm-6 emphasis">
                            <h2><strong> 20,7K </strong></h2>                    
                            <p><small>Followers</small></p>
                            <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>
                        </div>
                        <div class="col-xs-12 col-sm-6 emphasis">
                            <h2><strong>245</strong></h2>                    
                            <p><small>Following</small></p>
                            <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>
                        </div>
                    </div>
                </div>                 
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="posts">
                {% include "post.html" with posts=posts %}
            </div>
        </div>
        <div class="col-sm-3"></div>
    </div>  
{% endblock %}

profiles/templates/profiles/search.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <script>
        var token = "{{csrf_token}}";
        var folder_url = "{% url 'create-folder' %}";
        var root = false;
        var course = "{{course.id}}";
        var folder = "{{folder.id}}";
    </script>            
    <script src="{% static 'js/filesystem.js' %}"></script>   
    <link rel="stylesheet" type="text/css" href="{% static 'css/filesystem.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/upload.css' %}">
    <div class="card gedf-card">
        <div class="card-header">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#post-tab">Posts </a></li>
                <li><a data-toggle="tab" href="#resource-tab">Resources</a></li>
            </ul>              
            <div class="tab-content">
                <div id="post-tab" class="tab-pane fade in active">
                    <br>
                    <div class="posts">
                        {% include "post.html" with posts=post_list %}
                    </div>
                    {% if post_list.count == 0 %}
                        No Results
                    {% endif %}
                    <hr>
                </div>
                <div id="resource-tab" class="tab-pane fade">
                    <br>
                    {% for resource in resource_list %}
                        <hr>
                        <div class="item row">
                            <div class="col-sm-6">
                                <i class="fa fa-file" aria-hidden="true"></i>
                                <a href="{{resource.file.url}}">{{resource.title}}</a>
                            </div> 
                            <div class="col-sm-6">
                                {{resource.uploaded_on}}
                            </div> 
                        </div>
                    {% endfor %}
                    {% if resource_list.count == 0 %}
                        No Results
                    {% endif %}
                    <hr>
                </div>
            </div>
        </div>
    </div>

{% endblock %}